### ISSUE TITLE
FYI: docker build fails

### ISSUE THREAD

**Issue by enm10k** [geshan/docker-fabric-alpine#2]
I want to use `fabric.contrib.project.rsync_project` in fabfile.py.
http://docs.fabfile.org/en/1.12/api/contrib/project.html#fabric.contrib.project.rsync_project

So I tried to build a image by myself, but `docker build .` failed.
The version of py-paramiko seems to be incorrect.

```
$ docker build .
Sending build context to Docker daemon  5.12 kB
Step 1/5 : FROM alpine:edge
 ---> 9655ad68a6c9
Step 2/5 : MAINTAINER Geshan Manandhar (http://geshan.com.np)
 ---> Running in 1050fcb73a69
 ---> 01e2ac46c3bf
Removing intermediate container 1050fcb73a69
Step 3/5 : RUN apk --update add curl &&    apk add fabric --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted &&    rm /var/cache/apk/*
 ---> Running in f824cd4a177d
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ca-certificates (20161130-r0)
(2/4) Installing libssh2 (1.7.0-r2)
(3/4) Installing libcurl (7.52.1-r0)
(4/4) Installing curl (7.52.1-r0)
Executing busybox-1.25.1-r1.trigger
Executing ca-certificates-20161130-r0.trigger
OK: 5 MiB in 15 packages
fetch http://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/32) Installing py-crypto (2.6.1-r1)
(2/32) Installing py-cffi (1.8.3-r0)
(3/32) Installing py-idna (2.2-r0)
(4/32) Installing py-asn1 (0.1.9-r2)
(5/32) Installing py-six (1.10.0-r5)
(6/32) Installing py-cryptography (1.5.3-r0)
(7/32) Installing py-ecdsa (0.13-r4)
(8/32) Installing py-paramiko (2.0.2-r2)
(9/32) Installing libbz2 (1.0.6-r5)
(10/32) Installing expat (2.2.0-r0)
(11/32) Installing libffi (3.2.1-r2)
(12/32) Installing gdbm (1.12-r0)
(13/32) Installing ncurses-terminfo-base (6.0-r7)
(14/32) Installing ncurses-terminfo (6.0-r7)
(15/32) Installing ncurses-libs (6.0-r7)
(16/32) Installing readline (6.3.008-r4)
(17/32) Installing sqlite-libs (3.15.2-r0)
(18/32) Installing python2 (2.7.13-r0)
(19/32) Installing gmp (6.1.2-r0)
(20/32) Installing py2-crypto (2.6.1-r1)
(21/32) Installing py2-cparser (2.17-r0)
(22/32) Installing py2-cffi (1.8.3-r0)
(23/32) Installing py2-idna (2.2-r0)
(24/32) Installing py2-asn1 (0.1.9-r2)
(25/32) Installing py2-six (1.10.0-r5)
(26/32) Installing py2-ipaddress (1.0.17-r1)
(27/32) Installing py2-enum34 (1.1.6-r1)
(28/32) Installing py2-cryptography (1.5.3-r0)
(29/32) Installing py2-ecdsa (0.13-r4)
(30/32) Installing py2-paramiko (2.0.2-r2)
(31/32) Installing py-setuptools (32.3.0-r0)
(32/32) Installing fabric (1.11.1-r0)
Executing busybox-1.25.1-r1.trigger
OK: 66 MiB in 47 packages
 ---> 8f97204e3374
Removing intermediate container f824cd4a177d
Step 4/5 : WORKDIR /app
 ---> df446cbc39c5
Removing intermediate container 49a30dfac98e
Step 5/5 : VOLUME /app
 ---> Running in 4856d2e2f747
 ---> 9813ed94ed1a
Removing intermediate container 4856d2e2f747
Successfully built 9813ed94ed1a
$ docker run -it 9813ed94ed1a fab -l
Traceback (most recent call last):
  File "/usr/bin/fab", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'paramiko<2.0,>=1.10' distribution was not found and is required by Fabric
```

**Comment by geshan** [comment]
Will check this

**Comment by geshan** [comment]
@enm10k please check it now.

**Comment by enm10k** [comment]
@geshan Thanks! It works.
By the way, now I'm working on `rsync support`.
Are you interested in this? I will send a mr if you want.

**Comment by geshan** [comment]
send in a PR @enm10k I can give a look.
